name: Buildah
description: Buildkite plugin to wrap around buildah for building, pushing, and tagging docker images.
#TODO change to elastic
author: https://github.com/jmpavlec
requirements:
  - docker
  - vault
configuration:
  properties:
    docker_image_name:
      type: string
      description: The name of the resulting docker image
    dockerfile_path:
      type: string
      description: The full path from the base of the repo to the directory containing the Dockerfile
    vault_secret_path:
      type: string
      description: The vault path to get the secrets for the docker registry login
    docker_registry_path:
      type: string
      description: The full docker registry path. e.g. docker.elastic.co/cloud-ci/cloud-ui
    pre_build_steps:
      type: ['string', 'array']
      description: Commands to execute before the build takes places
    build_only:
      type: boolean
      description: Only build the docker image, don't push it
    additional_build_args:
      type: string
      description: Additional build args to buildah when building the docker image. e.g. --build-arg ui-app=userconsole
    tag:
      type: string
      description: Additional tags to add to the docker image. Default is BUILDKITE_COMMIT up to character 7. e.g. ${BUILDKITE_COMMIT:0:7} '01161e5'
  required: ['docker_image_name', 'dockerfile_path', 'vault_secret_path', 'docker_registry_path']
